version: "3"
services:
  validator-voluntary-exit:
# This is a beta.2 image for Medalla. Change target to "stable" for Pyrmont and on
    image: prysmaticlabs/prysm-validator:HEAD-d4c954-debug
    restart: "no"
    volumes:
      - ./.eth2/accept:/home/.eth2
      - ./.eth2:/setup:ro
      - ./.eth2/validator_keys:/keys:ro
    environment:
      - BEACON=${BEACON}
      - TESTNET=${TESTNET}
    entrypoint: sh
    command: "/setup/process-exit.sh"
